name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{matrix.platform.os}}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Ubuntu,            os: ubuntu-latest,  shell: sh }
        - { name: Windows - mingw32, os: windows-latest, shell: 'msys2 {0}', msystem: mingw32, msys-env: mingw-w64-i686 }
        - { name: Windows - mingw64, os: windows-latest, shell: 'msys2 {0}', msystem: mingw64, msys-env: mingw-w64-x86_64 }
        build-type: [Release]
        build-static: [ON]
    steps:
    - uses: actions/checkout@v3

    - name: Setup GNU/Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install \
            libssl-dev ninja-build zlib1g-dev

    - name: Setup Windows dependencies
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.platform.msystem}}
        install: >-
          ${{matrix.platform.msys-env}}-gcc
          ${{matrix.platform.msys-env}}-cmake
          ${{matrix.platform.msys-env}}-ninja
          ${{matrix.platform.msys-env}}-openssl
          ${{matrix.platform.msys-env}}-zlib

    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DBUILD_STATIC=${{matrix.build-static}}

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: build
      run: ctest --output-on-failure
